language: node_js
node_js:
  - "node"
sudo: false
branches:
  only:
  - dev
install:
- npm install
script:
- hexo g -f
after_script:
  - cd ./public
  - git init
  - git config user.name "hiramgao"
  - git config user.email "hiramgao@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blogToken}@${GH_REF}" master:master

cache:
  directories:
  - node_modules
env:
  global:
    - GH_REF: github.com/HiramGao/hiramgao.github.io.git
