language: node_js
node_js:
  - "node"
sudo: false
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_24f627a79d15_key -iv $encrypted_24f627a79d15_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'hiramgao'
- git config --global user.email hiramgao@163.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
cache:
  directories:
  - node_modules
